### ISSUE TITLE
Opcodes folder was changed in Tera Toolbox

### ISSUE THREAD

**Issue by Feuerstahl** [Owyn/alex-packet-id-finder#5]
opcodes folder was changed from 
...\TeraToolbox\node_modules\tera-data\map to ...\TeraToolbox\data\opcodes
and definitions folder was changed also from
...\TeraToolbox\node_modules\tera-data\protocol to ...\TeraToolbox\data\definitions
since Toolbox update (01.03.2020)

**Comment by Owyn** [comment]
does this matter? 🤔

**Comment by Feuerstahl** [comment]
if i delete the tera-data folder the mod will be broken

**Comment by Feuerstahl** [comment]
I did a fresh install of Toolbox in a separate folder just to compare the differences.
The tera-data folder won't exist anymore inside the node_modules folder.
I guess the mod won't work in an fresh tollbox installation.

Edit:
Now I unzipped the mod in ...\TeraToolbox\mods, started Proxy + Tera and get this Error
`[22:45:03.060] [mods] ERROR: Module "ID-Finder" (Alex Packet-ID finder) could not be loaded!
[22:45:03.062] [mods] ERROR: Please contact the module's author: https://github.com/Owyn/
[22:45:03.066] Error: Cannot find module 'tera-data'
Require stack:
- C:\Users\onkelj666\Desktop\Test\TeraToolbox\mods\alex-packet-id-finder-master\index.js
- C:\Users\onkelj666\Desktop\Test\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js
- C:\Users\onkelj666\Desktop\Test\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js
- C:\Users\onkelj666\Desktop\Test\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js
- C:\Users\onkelj666\Desktop\Test\TeraToolbox\node_modules\tera-network-proxy\lib\index.js
- C:\Users\onkelj666\Desktop\Test\TeraToolbox\bin\connectionManager.js
- C:\Users\onkelj666\Desktop\Test\TeraToolbox\bin\proxy.js
- C:\Users\onkelj666\Desktop\Test\TeraToolbox\bin\loader-gui.js
- C:\Users\onkelj666\Desktop\Test\TeraToolbox\bin\index-gui.js
- C:\Users\onkelj666\Desktop\Test\TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7595:16)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at findPacketDefList (C:\Users\onkelj666\Desktop\Test\TeraToolbox\mods\alex-packet-id-finder-master\index.js:82:26)
    at new AlexPacketIdFinder (C:\Users\onkelj666\Desktop\Test\TeraToolbox\mods\alex-packet-id-finder-master\index.js:7:38)
    at ModuleManager.load (C:\Users\onkelj666\Desktop\Test\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at C:\Users\onkelj666\Desktop\Test\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\onkelj666\Desktop\Test\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (C:\Users\onkelj666\Desktop\Test\TeraToolbox\bin\connectionManager.js:55:47) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\onkelj666\\Desktop\\Test\\TeraToolbox\\mods\\alex-packet-id-finder-master\\index.js',
    'C:\\Users\\onkelj666\\Desktop\\Test\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\moduleManager.js',
    'C:\\Users\\onkelj666\\Desktop\\Test\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\index.js',
    'C:\\Users\\onkelj666\\Desktop\\Test\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\index.js',
    'C:\\Users\\onkelj666\\Desktop\\Test\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\index.js',
    'C:\\Users\\onkelj666\\Desktop\\Test\\TeraToolbox\\bin\\connectionManager.js',
    'C:\\Users\\onkelj666\\Desktop\\Test\\TeraToolbox\\bin\\proxy.js',
    'C:\\Users\\onkelj666\\Desktop\\Test\\TeraToolbox\\bin\\loader-gui.js',
    'C:\\Users\\onkelj666\\Desktop\\Test\\TeraToolbox\\bin\\index-gui.js',
    'C:\\Users\\onkelj666\\Desktop\\Test\\TeraToolbox\\node_modules\\electron\\dist\\resources\\default_app.asar\\main.js',
    undefined
  ]
}`

**Comment by Owyn** [comment]
well, then RIP mod 🤷‍♀  unless someone comes and fixes it

or you can just get full opcodes from pinky's tera-data

**Comment by Feuerstahl** [comment]
Caali said in his Toolbox Discord
`The next big Toolbox update has been released! It includes multiple performance improvements and QoL changes.

Changes
- Electron self-update no longer requires Node.JS. This means that GUI users don't need to install Node anymore.
- Update to Electron 8 & add support for Node 13
- Toolbox now requires a 64bit OS. Support for 32bit OS & Windows XP was dropped (not sure about Vista, but 7-10 should work fine)
- Replace request by node-fetch and remove a ton of no longer required node_modules (from ~100 down to 2 + Electron if you're using GUI), making Toolbox much more lightweight and shortening startup time.
- Replace node-process-list/injector.exe with a custom native node_module that handles scan & injection in a dedicated thread. This means lower idle CPU usage (when you're not playing) and much faster launch detection, resulting in fewer failed GPK mod installs.
- Distribute tera-data as a single-file bundle instead of hundreds of individual files. This greatly speeds up auto-updating and startup. Furthermore, there's now a clean distinction between default and custom opcodes/definitions. Custom ones are stored in subfolders of  [toolbox]/data/. The [toolbox]/node_modules/tera-data folder is no longer used. Note: Toolbox won't delete it so your custom files are preserved. Please copy custom files and delete the folder yourself, or perform a clean reinstall!
- Improved packet def compiler, resulting in massive performance improvements.
- Updated installer`

i searched for the file and found one in ...\TeraToolbox\data called data.json
 
the code looks like
`{"maps":{"343506":{"C_ACCEPT_CONTRACT":50196,"C_ACCEPT_GUILD_APPLY":59460,"C_ADD_FRIEND":42715,"C_ADD_INTER_PARTY_MATCH_POOL":50181,"C_ADD_ITEM_TO_VM_BUY_BASKET":58817,"C_ADD_ITEM_TO_VM_SELL_BASKET":24145,"C_ADD_TELEPORT_TO_POS_LIST":48102,"C_ADD_TO_TEMPER_MATERIAL_EX":44364,"C_ADD_TRADE_BAG":39424,"C_ADMIN":35732,"C_ADMIN_ADD_CUSTOM_BOOKMARK":48787,"C_ADMIN_CHAT_BAN":37560,"C_ADMIN_CHECK_USERNAME":24993,"C_ADMIN_CHECK_USERNAME_WITH_GAMEID":30811,"C_ADMIN_GET_USER_INFO_BY_DBID":36209,`
and so on

**Comment by Owyn** [comment]
see if it works with latest id-finder version, I've been told it should

**Comment by Feuerstahl** [comment]
now it works
